### ISSUE TITLE
What happened to zach.is-awesome.cool???

### ISSUE THREAD

**Issue by flotwig** [sebastianbarfurth/is-awesome.cool#1]
Melon, I don't know what I did to deserve this :( the individual subdomain pages no longer work

https://i.imgur.com/m6Iwb3P.png

**Comment by sbarfurth** [comment]
The site is hosted statically via GitHub, sadly that makes subdomains hard. Got a solution?

**Comment by flotwig** [comment]
Hmm, not now that it's static. If you wanted to CNAME *.is-awesome.cool => overflod.chary.us I could run the server on there

Or you could use `window.location.hash` to make http://is-awesome.cool/#zach do the old behavior, but the domain name makes even less sense like that

**Comment by sbarfurth** [comment]
That's how it is now, it will use whatever is after the /, so http://is-awesome.cool/zach works. It's fairly simple to make it dynamic again, but it needs a server. I would wanna build it in Flask to learn it. If you have a server I can get that done.

Also @noeatnosleep controls the domain, would need hold of him. I've always just been the code maintainer.

**Comment by flotwig** [comment]
Drop me an SSH pubkey, I'll get you set up with an account tonight. I can coordinate with nens to get the CNAME done

**Comment by flotwig** [comment]
@noeatnosleep once you figure out where the domain is hosted, can you please change the nameservers to the below?

```
rita.ns.cloudflare.com
rick.ns.cloudflare.com
```

**Comment by noeatnosleep** [comment]
Sure. I'm struggling to find it. I'm not positive that I do own it. We have any other ideas of who might own it?

**Comment by sbarfurth** [comment]
What kind of first world problem is not knowing where a domain is hosted, we have actually lost a domain.

I’m pretty sure it’s yours, or someone else that starts with an “n”.

**Comment by noeatnosleep** [comment]
nekosune?

**Comment by sbarfurth** [comment]
I’m 85% sure it’s you, but that would be the other option I guess. I’m 98% sure about the “n”.

**Comment by noeatnosleep** [comment]
Alright, I'll look around and ask around.

**Comment by flotwig** [comment]
@sebastianbarfurth any ideas? I'm drawing a blank.

**Comment by sbarfurth** [comment]
@flotwig Sent you a key!

@noeatnosleep In hindsight it may be nekosune because I feel like I remember it being someone not that tech savvy.

**Comment by noeatnosleep** [comment]
Haha. That would actually describe me... But I actually am fairly certain it was Nalixor after asking around. I'll verify when they're awake and online.

**Comment by sbarfurth** [comment]
Well my "n" theory holds true!

**Comment by flotwig** [comment]
Got it up and running, good stuff guys. Also SSL-secured so nobody will intercept your important transmissions, thank God for Let's Encrypt.

https://sebastian.is-awesome.cool !!
https://noeatnosleep.is-awesome.cool !
https://nalixor.is-awesome.cool !

**Comment by sbarfurth** [comment]
Great! Thanks @flotwig!
